# Generated by Django 5.2.7 on 2025-10-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_feature_thread"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Thread",
            new_name="Threat",
        ),
    ]
