# Generated by Django 5.2.7 on 2025-10-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_thread_threat"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Software",
        ),
        migrations.AlterModelOptions(
            name="software",
            options={"ordering": ["name"], "verbose_name_plural": "software"},
        ),
        migrations.RenameField(
            model_name="component",
            old_name="product",
            new_name="software",
        ),
    ]
