# Generated by Django 5.1.9 on 2025-10-20 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_product_software_alter_software_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=2
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "To Do"), (2, "In Progress"), (3, "Done")],
                        default=1,
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_features",
                        to="core.feature",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_features",
                        to="core.software",
                    ),
                ),
            ],
            options={
                "ordering": ["software__name", "feature__name"],
                "unique_together": {("software", "feature")},
            },
        ),
    ]
