# Generated by Django 5.1.9 on 2025-10-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_softwarefeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=2
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "To Do"), (2, "In Progress"), (3, "Done")],
                        default=1,
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_features",
                        to="core.component",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_features",
                        to="core.feature",
                    ),
                ),
            ],
            options={
                "ordering": ["component__name", "feature__name"],
                "unique_together": {("component", "feature")},
            },
        ),
        migrations.AddField(
            model_name="feature",
            name="components",
            field=models.ManyToManyField(
                related_name="features",
                through="core.ComponentFeature",
                to="core.component",
            ),
        ),
        migrations.DeleteModel(
            name="SoftwareFeature",
        ),
    ]
