# Generated by Django 5.2.7 on 2025-10-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_componentfeature_feature_components_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentfeature",
            name="name",
        ),
    ]
