# Generated by Django 5.2.7 on 2025-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_componentfeature_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentfeature",
            name="jira_ticket_url",
            field=models.URLField(blank=True),
        ),
    ]
