# Generated by Django 5.2.7 on 2025-10-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_componentfeature_jira_ticket_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="business_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="component",
            name="engineering_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
