# Generated by Django 5.2.7 on 2025-10-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_component_business_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("execution_start_date", models.DateField(blank=True)),
                ("execution_end_date", models.DateField(blank=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "To Do"), (2, "In Progress"), (3, "Done")],
                        default=1,
                    ),
                ),
                ("component_version", models.CharField(blank=True, max_length=100)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.component",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["name"],
            },
        ),
    ]
