# Generated by Django 5.2.7 on 2025-10-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="execution_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="execution_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
