# Generated by Django 5.2.7 on 2025-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_activity_execution_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("name", "component")},
        ),
    ]
