# Generated by Django 5.2.7 on 2025-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_activity_name_alter_activity_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="jira_ticket_url",
            field=models.URLField(blank=True),
        ),
    ]
