# Generated by Django 5.1.9 on 2025-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_component_jira_ticket_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="dev_preview_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="general_availability_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="component",
            name="tech_preview_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
