# Generated by Django 5.2.7 on 2025-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_link_document_jiraticket_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="psrd_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
