# Generated by Django 5.2.7 on 2025-11-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_component_psrd_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.activity"
                    ),
                ),
            ],
            options={
                "ordering": ["activity__name", "campaign__name"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "To Do"), (2, "In Progress"), (3, "Done")],
                        default=1,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("jira_ticket_url", models.URLField(blank=True)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "activities",
                    models.ManyToManyField(
                        related_name="campaigns",
                        through="core.ActivityCampaign",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="activitycampaign",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.campaign"
            ),
        ),
        migrations.CreateModel(
            name="FeatureCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.campaign"
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.feature"
                    ),
                ),
            ],
            options={
                "ordering": ["feature__name", "campaign__name"],
                "unique_together": {("feature", "campaign")},
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="features",
            field=models.ManyToManyField(
                related_name="campaigns",
                through="core.FeatureCampaign",
                to="core.feature",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activitycampaign",
            unique_together={("activity", "campaign")},
        ),
    ]
