# Generated by Django 5.2.7 on 2025-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_activitycampaign_campaign_activitycampaign_campaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="estimated_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
