# Generated by Django 5.2.7 on 2025-11-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_activity_estimated_completion_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="features",
        ),
        migrations.CreateModel(
            name="ComponentFeatureCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.campaign"
                    ),
                ),
                (
                    "component_feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.componentfeature",
                    ),
                ),
            ],
            options={
                "ordering": ["component_feature__feature__name", "campaign__name"],
                "unique_together": {("component_feature", "campaign")},
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="component_features",
            field=models.ManyToManyField(
                related_name="campaigns",
                through="core.ComponentFeatureCampaign",
                to="core.componentfeature",
            ),
        ),
        migrations.DeleteModel(
            name="FeatureCampaign",
        ),
    ]
