# Generated by Django 5.2.7 on 2025-11-18 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_campaign_features_componentfeaturecampaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="component_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.componentfeature",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.activity",
            ),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_tickets",
                to="core.activity",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="core.activity",
            ),
        ),
    ]
