# Generated by Django 5.2.7 on 2025-12-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_featurecategory_feature_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.activity"
                    ),
                ),
            ],
            options={
                "ordering": ["activity__name", "requirement__name"],
            },
        ),
        migrations.CreateModel(
            name="ComponentStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.component"
                    ),
                ),
            ],
            options={
                "ordering": ["component__name", "standard__name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.feature"
                    ),
                ),
            ],
            options={
                "ordering": ["feature__name", "requirement__name"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
                ("name", models.CharField(blank=True, max_length=300)),
                ("code", models.CharField(blank=True, max_length=100)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "activities",
                    models.ManyToManyField(
                        related_name="requirements",
                        through="core.ActivityRequirement",
                        to="core.activity",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="requirements",
                        through="core.FeatureRequirement",
                        to="core.feature",
                    ),
                ),
            ],
            options={
                "ordering": ["standard__name", "definition"],
            },
        ),
        migrations.AddField(
            model_name="featurerequirement",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.requirement"
            ),
        ),
        migrations.AddField(
            model_name="activityrequirement",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.requirement"
            ),
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "components",
                    models.ManyToManyField(
                        related_name="standards",
                        through="core.ComponentStandard",
                        to="core.component",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="requirement",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.standard"
            ),
        ),
        migrations.AddField(
            model_name="componentstandard",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.standard"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featurerequirement",
            unique_together={("feature", "requirement")},
        ),
        migrations.AlterUniqueTogether(
            name="activityrequirement",
            unique_together={("activity", "requirement")},
        ),
        migrations.AlterUniqueTogether(
            name="requirement",
            unique_together={("standard", "definition")},
        ),
        migrations.AlterUniqueTogether(
            name="componentstandard",
            unique_together={("component", "standard")},
        ),
    ]
