# Generated by Django 5.2.7 on 2025-12-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_activityrequirement_componentstandard_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requirement",
            options={"ordering": ["creation_datetime"]},
        ),
        migrations.AlterField(
            model_name="requirement",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="core.standard",
            ),
        ),
        migrations.CreateModel(
            name="ComponentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                ("execution_start_date", models.DateField(blank=True, null=True)),
                ("execution_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "To Do"), (2, "In Progress"), (3, "Done")],
                        default=1,
                    ),
                ),
                ("component_version", models.CharField(blank=True, max_length=100)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_activities",
                        to="core.activity",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_activities",
                        to="core.component",
                    ),
                ),
            ],
            options={
                "ordering": ["component__name", "activity__name"],
                "unique_together": {("component", "activity")},
            },
        ),
    ]
