# Generated by Django 5.2.7 on 2025-12-02 12:20

from django.db import migrations

def migrate_activities(apps, schema_editor):
    Activity = apps.get_model('core', 'Activity')
    ComponentActivity = apps.get_model('core', 'ComponentActivity')
    
    # Agrupar por nombre único
    activities_by_name = {}
    for activity in Activity.objects.all():
        name = activity.name
        if name not in activities_by_name:
            activities_by_name[name] = []
        activities_by_name[name].append(activity)
    
    for name, duplicates in activities_by_name.items():
        # Mantener el primero como Activity única
        master_activity = duplicates[0]
        
        # Crear ComponentActivity para cada duplicado (incluyendo el master si tiene component)
        for activity in duplicates:
            if hasattr(activity, 'component_id') and activity.component_id:
                ComponentActivity.objects.create(
                    activity=master_activity,
                    estimated_completion_date=activity.estimated_completion_date,
                    execution_start_date=activity.execution_start_date,
                    execution_end_date=activity.execution_end_date,
                    status=activity.status,
                    component_version=activity.component_version or '',
                    component_id=activity.component_id,
                )
        
        # Eliminar duplicados (excepto el master)
        for dup in duplicates[1:]:
            dup.delete()

def reverse_migrate(apps, schema_editor):
    # Función reversa (vacía por simplicidad)
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_requirement_options_alter_requirement_standard_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_activities, reverse_migrate),
    ]
