# Generated by Django 5.2.7 on 2025-12-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_migrate_activities_to_componentactivities"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="document",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="jiraticket",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="result",
            name="activity",
        ),
        migrations.AddField(
            model_name="document",
            name="component_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.componentactivity",
            ),
        ),
        migrations.AddField(
            model_name="jiraticket",
            name="component_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_tickets",
                to="core.componentactivity",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="component_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="core.componentactivity",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name="activity",
            name="component",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="component_version",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="estimated_completion_date",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="execution_end_date",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="execution_start_date",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="status",
        ),
    ]
