# Generated by Django 5.2.7 on 2025-12-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_activity_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentActivityCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.campaign"
                    ),
                ),
                (
                    "component_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.componentactivity",
                    ),
                ),
            ],
            options={
                "ordering": ["component_activity__activity__name", "campaign__name"],
                "unique_together": {("component_activity", "campaign")},
            },
        ),
    ]
