# Generated by Django 5.2.7 on 2025-12-02 15:13

from django.db import migrations

def migrate_activitycampaign_to_componentactivitycampaign(apps, schema_editor):
    ActivityCampaign = apps.get_model('core', 'ActivityCampaign')
    ComponentActivity = apps.get_model('core', 'ComponentActivity')
    ComponentActivityCampaign = apps.get_model('core', 'ComponentActivityCampaign')

    for ac in ActivityCampaign.objects.all():
        component_activities = ComponentActivity.objects.filter(activity=ac.activity)
        for ca in component_activities:
            ComponentActivityCampaign.objects.create(
                component_activity=ca,
                campaign=ac.campaign,
                creation_datetime=ac.creation_datetime,
                modification_datetime=ac.modification_datetime,
            )

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_componentactivitycampaign"),
    ]

    operations = [
        migrations.RunPython(migrate_activitycampaign_to_componentactivitycampaign),
    ]
