# Generated by Django 5.2.7 on 2025-12-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_migrate_activitycampaign_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="activities",
        ),
        migrations.AddField(
            model_name="campaign",
            name="component_activities",
            field=models.ManyToManyField(
                related_name="campaigns",
                through="core.ComponentActivityCampaign",
                to="core.componentactivity",
            ),
        ),
    ]
