# Generated by Django 5.2.7 on 2025-12-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_campaign_activities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jiraticket",
            name="component_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jira_tickets",
                to="core.componentfeature",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="component_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="core.componentfeature",
            ),
        ),
    ]
