# Generated by Django 5.2.7 on 2025-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_jiraticket_component_feature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentactivitycampaign",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
