# Generated by Django 5.2.7 on 2025-12-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_componentactivitycampaign_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentactivitycampaign",
            name="notes",
        ),
        migrations.AddField(
            model_name="componentactivity",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
