# Generated by Django 5.2.7 on 2025-12-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_componentactivitycampaign_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Engineering", "Engineering"),
                            ("Business", "Business"),
                            ("PSRD", "PSRD"),
                        ],
                        max_length=100,
                    ),
                ),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("modification_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "email")},
            },
        ),
        migrations.AddField(
            model_name="component",
            name="business_contact_fk",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "Business"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_components",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="engineering_contact_fk",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "Engineering"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="engineering_components",
                to="core.contact",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="psrd_contact_fk",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "PSRD"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="psrd_components",
                to="core.contact",
            ),
        ),
    ]
