# Generated by Django 5.2.7 on 2025-12-15 12:19

from django.db import migrations

def populate_contacts(apps, schema_editor):
    Component = apps.get_model('core', 'Component')
    Contact = apps.get_model('core', 'Contact')

    for comp in Component.objects.all():
        if comp.engineering_contact:
            contact, created = Contact.objects.get_or_create(
                name=comp.engineering_contact,
                defaults={'type': 'Engineering', 'email': ''}
            )
            comp.engineering_contact_fk = contact
            comp.save(update_fields=['engineering_contact_fk'])

        if comp.business_contact:
            contact, created = Contact.objects.get_or_create(
                name=comp.business_contact,
                defaults={'type': 'Business', 'email': ''}
            )
            comp.business_contact_fk = contact
            comp.save(update_fields=['business_contact_fk'])

        if comp.psrd_contact:
            contact, created = Contact.objects.get_or_create(
                name=comp.psrd_contact,
                defaults={'type': 'PSRD', 'email': ''}
            )
            comp.psrd_contact_fk = contact
            comp.save(update_fields=['psrd_contact_fk'])

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_contact_component_business_contact_fk_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_contacts),
    ]
