# Generated by Django 5.2.7 on 2025-12-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20251215_1219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="business_contact",
        ),
        migrations.RemoveField(
            model_name="component",
            name="engineering_contact",
        ),
        migrations.RemoveField(
            model_name="component",
            name="psrd_contact",
        ),
        migrations.RenameField(
            model_name="component",
            old_name="business_contact_fk",
            new_name="business_contact",
        ),
        migrations.RenameField(
            model_name="component",
            old_name="engineering_contact_fk",
            new_name="engineering_contact",
        ),
        migrations.RenameField(
            model_name="component",
            old_name="psrd_contact_fk",
            new_name="psrd_contact",
        ),
    ]
