from django.urls import path
from . import views as core_views


urlpatterns = [
    path('', core_views.SoftwareList.as_view(), name='home'),
    path('software/', core_views.SoftwareList.as_view(), name='software_list'),
    path('software/<int:pk>/', core_views.SoftwareDetail.as_view(), name='software_detail'),
    path('software/add/', core_views.SoftwareCreate.as_view(), name='software_add'),
    path('software/<int:pk>/edit/', core_views.SoftwareUpdate.as_view(), name='software_update'),
    path('software/<int:pk>/delete/', core_views.SoftwareDelete.as_view(), name='software_delete'),
    path('software/<int:software_pk>/components/add/', core_views.ComponentCreate.as_view(), name='component_add_to_software'),
    path('components/<int:pk>/', core_views.ComponentDetail.as_view(), name='component_detail'),
    path('components/add/', core_views.ComponentCreate.as_view(), name='component_add'),
    path('components/<int:pk>/edit/', core_views.ComponentUpdate.as_view(), name='component_update'),
    path('components/<int:pk>/delete/', core_views.ComponentDelete.as_view(), name='component_delete'),
    path('componentfeature/<int:pk>/delete/', core_views.ComponentFeatureDelete.as_view(), name='componentfeature_delete'),
    path('features/', core_views.FeatureList.as_view(), name='feature_list'),
    path('features/<int:pk>/', core_views.FeatureDetail.as_view(), name='feature_detail'),
    path('features/add/', core_views.FeatureCreate.as_view(), name='feature_add'),
    path('features/<int:pk>/edit/', core_views.FeatureUpdate.as_view(), name='feature_update'),
    path('features/<int:pk>/delete/', core_views.FeatureDelete.as_view(), name='feature_delete'),
    path('threats/', core_views.ThreatList.as_view(), name='threat_list'),
    path('threats/<int:pk>/', core_views.ThreatDetail.as_view(), name='threat_detail'),
    path('threats/add/', core_views.ThreatCreate.as_view(), name='threat_add'),
    path('threats/<int:pk>/edit/', core_views.ThreatUpdate.as_view(), name='threat_update'),
    path('threats/<int:pk>/delete/', core_views.ThreatDelete.as_view(), name='threat_delete'),
    path('activities/', core_views.ActivityList.as_view(), name='activity_list'),
    path('activities/<int:pk>/', core_views.ActivityDetail.as_view(), name='activity_detail'),
    path('activities/add/', core_views.ActivityCreate.as_view(), name='activity_add'),
    path('components/<int:component_pk>/activities/add/', core_views.ActivityCreate.as_view(), name='activity_add_to_component'),
    path('activities/<int:pk>/edit/', core_views.ActivityUpdate.as_view(), name='activity_update'),
    path('activities/<int:pk>/delete/', core_views.ActivityDelete.as_view(), name='activity_delete'),
    path('campaigns/', core_views.CampaignList.as_view(), name='campaign_list'),
    path('campaigns/<int:pk>/', core_views.CampaignDetail.as_view(), name='campaign_detail'),
    path('campaigns/add/', core_views.CampaignCreate.as_view(), name='campaign_add'),
    path('campaigns/<int:pk>/edit/', core_views.CampaignUpdate.as_view(), name='campaign_update'),
    path('campaigns/<int:pk>/delete/', core_views.CampaignDelete.as_view(), name='campaign_delete'),
]
